#!/run/current-system/sw/bin/quickemu --vm
guest_os="linux"
disk_img="ubuntu-22.04-open5gs/disk.qcow2"
iso="ubuntu-22.04-open5gs/ubuntu-22.04.5-desktop-amd64.iso"

ram="4G"
cpu_cores="4"
disk_size="30G"

#network="br-5g"

# NixOS specific workaround: https://discourse.nixos.org/t/quickgui-with-bridged-networking-failed-to-create-tun-device/75893
network="none"
